apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy04
  labels:
    app: autodeploy04
  namespace: namespace-workflow-1700126604621
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy04
  template:
    metadata:
      labels:
        app: autodeploy04
    spec:
      containers:
        - name: autodeploy04
          image: acrworkflow1700126604621.azurecr.io/image-workflow-1700126604621:latest
          ports:
            - containerPort: 5000